version: '3.8'

services:
  backend:
    build: .
    image: lunaria-backend:latest
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DBNAME}?sslmode=${POSTGRES_SSLMODE}
      - MONGODB_URI=mongodb://mongo:27017/${MONGODB_DATABASE}
      - REDIS_URL=redis://redis:6379/0
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_ENVIRONMENT=${SERVER_ENVIRONMENT}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_USE_PATH_STYLE=${S3_USE_PATH_STYLE}
      - GROK_API_KEY=${GROK_API_KEY}
      - GROK_MODEL=${GROK_MODEL}
      - GROK_MINI_MODEL=${GROK_MINI_MODEL}
      - GROK_MAX_TOKENS=${GROK_MAX_TOKENS}
      - GROK_TEMPERATURE=${GROK_TEMPERATURE}
      - GROK_BASE_URL=${GROK_BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRY=${JWT_ACCESS_EXPIRY}
      - JWT_REFRESH_EXPIRY=${JWT_REFRESH_EXPIRY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
    ports:
      - "8080:8080"
      - "6060:6060"
    depends_on:
      - postgres
      - mongo
      - redis

  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  mongodata:
  redisdata: 